Wallet generation Successful!
{"tradeId": "TXID018869975905", "memonic": "CZVUGECnThszeLiCpx4UkqJmQOFu4tYrC/DJ2jomti9jiwkglQEQJji9XgDRnrkx3QqHsY/zOYyd1zzYS/X3KYKjt/ESK1ev3+34iZrQ0Scwp/4rPxHAPYRx/KCIX6ezlw==", "secretKey": "D8ZWU4QIhvWbZWD5lafsQhAhFFDIx8k7lsDtTJpwu5W7c2r/B6QDj6FTSYZhGkZcpj0LQAjQd/q/f5wOmgEhjVDsGhS1HfRFM02JzLt7kOU=", "publicKey": "5Mxq31EJwCKB2tgQR21M6GxsF19iD2DTro52C2fSpyDy", "currency": "SOL", "tradeType": "futures", "__time_added": 1725711141}
Initiating transaction for Trade ID: TXID018869975905
Sender: 5Mxq31EJwCKB2tgQR21M6GxsF19iD2DTro52C2fSpyDy, Recipient: 2amQyqkkagxjnKbzHJW5QsdfzdfvVBaMoKakdU27Dv1w, Amount: 40 USDT
Token account does not exist. Creating token account...
adding charges to out wallet
An error occurred: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction", data: RpcSimulateTransactionResult(RpcSimulateTransactionResult { err: Some(InstructionError(1, InvalidAccountData)), logs: Some(["Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]", "Program log: Create", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: GetAccountDataSize", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 594408 compute units", "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program 11111111111111111111111111111111 invoke [2]", "Program 11111111111111111111111111111111 success", "Program log: Initialize the associated token account", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: InitializeImmutableOwner", "Program log: Please upgrade to SPL Token 2022 for immutable owner support", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 587768 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: InitializeAccount3", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 583884 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20695 of 600000 compute units", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]", "Program log: Instruction: TransferChecked", "Program log: Error: InvalidAccountData", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1456 of 579305 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"]), accounts: None, units_consumed: Some(22151), return_data: None, inner_instructions: None }) }
Traceback (most recent call last):
  File "D:\cryptoEscrow\imports\usdt_sol_sender.py", line 170, in send_transaction
    result = client.send_raw_transaction(txn=bytes(transaction), opts=opts)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\solana\rpc\api.py", line 994, in send_raw_transaction
    resp = self._provider.make_request(body, SendTransactionResp)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\solana\exceptions.py", line 45, in argument_decorator
    return func(*args, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\solana\rpc\providers\http.py", line 49, in make_request
    return _parse_raw(raw, parser=parser)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\solana\rpc\providers\core.py", line 98, in _parse_raw
    raise RPCException(parsed)
solana.rpc.core.RPCException: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction", data: RpcSimulateTransactionResult(RpcSimulateTransactionResult { err: Some(InstructionError(1, InvalidAccountData)), logs: Some(["Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]", "Program log: Create", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: GetAccountDataSize", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 594408 compute units", "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program 11111111111111111111111111111111 invoke [2]", "Program 11111111111111111111111111111111 success", "Program log: Initialize the associated token account", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: InitializeImmutableOwner", "Program log: Please upgrade to SPL Token 2022 for immutable owner support", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 587768 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]", "Program log: Instruction: InitializeAccount3", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 583884 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20695 of 600000 compute units", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]", "Program log: Instruction: TransferChecked", "Program log: Error: InvalidAccountData", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1456 of 579305 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"]), accounts: None, units_consumed: Some(22151), return_data: None, inner_instructions: None }) }

Transaction for Trade ID TXID018869975905 completed
