Sending 998000 Satoshi with fee of 2000
UTXO value: 1000000
Unsigned TX: {'tx': {'block_height': -1, 'block_index': -1, 'hash': '4ed602b80953a918d4c53e36f2a28c297648b7698415e9133c88404a562ce17f', 'addresses': ['ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96', 'ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n'], 'total': 998000, 'fees': 2000, 'size': 116, 'vsize': 116, 'preference': 'medium', 'relayed_by': '2409:40c4:201b:d043:411c:c580:597d:784', 'received': '2024-08-07T07:32:12.111380744Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'a43cdfb811f055834de8d7dfad054435dc706a0f12159a478ae3db5de09d8351', 'output_index': 0, 'output_value': 1000000, 'sequence': 4294967295, 'addresses': ['ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96'], 'script_type': 'pay-to-witness-pubkey-hash', 'age': 2733785}], 'outputs': [{'value': 998000, 'script': '00148cef6940c2d37e964856c390acd7db5d93ee8218', 'addresses': ['ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n'], 'script_type': 'pay-to-witness-pubkey-hash'}]}, 'tosign': ['de633f0c7185ca1e6f17e45bd1af5896ed1c1595a4545f69286cccd086a819ef']}
Signed signatures: ['3044022010a2ba3a7450d9fa61fe486cf4b28a46e1d41f31dbd404e62c9f11ffc569042602205f52f1790c5b9abebee951fed359bc22c97ccde101e20b8179f2a9703a422c3701']
Broadcasting TX
Transaction hash: 4ed602b80953a918d4c53e36f2a28c297648b7698415e9133c88404a562ce17f
Transaction Push Response: {'tx': {'block_height': -1, 'block_index': -1, 'hash': '4ed602b80953a918d4c53e36f2a28c297648b7698415e9133c88404a562ce17f', 'addresses': ['ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96', 'ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n'], 'total': 998000, 'fees': 2000, 'size': 191, 'vsize': 110, 'preference': 'low', 'relayed_by': '2409:40c4:201b:d043:411c:c580:597d:784', 'received': '2024-08-07T07:32:16.312440525Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'a43cdfb811f055834de8d7dfad054435dc706a0f12159a478ae3db5de09d8351', 'output_index': 0, 'output_value': 1000000, 'sequence': 4294967295, 'addresses': ['ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96'], 'script_type': 'pay-to-witness-pubkey-hash', 'age': 2733785, 'witness': ['3044022010a2ba3a7450d9fa61fe486cf4b28a46e1d41f31dbd404e62c9f11ffc569042602205f52f1790c5b9abebee951fed359bc22c97ccde101e20b8179f2a9703a422c3701', '02e0ae731de7ab401f6a98b326690336999838ab101fab790b0a6a67de1abff225']}], 'outputs': [{'value': 998000, 'script': '00148cef6940c2d37e964856c390acd7db5d93ee8218', 'addresses': ['ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n'], 'script_type': 'pay-to-witness-pubkey-hash'}]}, 'tosign': ['']}
Sending 998000 Satoshi with fee of 2000
UTXO value: 1000000
An error occurred: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 88, in send_ltc_transaction
    unsigned_tx = create_unsigned_tx(inputs=inputs, outputs=outputs, coin_symbol='ltc', api_key=api_token)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\blockcypher\api.py", line 1456, in create_unsigned_tx
    r = requests.post(url, json=data, params=params, verify=True, timeout=TIMEOUT_IN_SECONDS)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Read timed out. (read timeout=10)

Sending 998000 Satoshi with fee of 2000
UTXO value: 1000000
Unsigned TX: {'tx': {'block_height': -1, 'block_index': -1, 'hash': '6c4416ffe9db6f32fb6c0aafa2cd858989ddf92e67176979c57ea57f35077da4', 'addresses': ['ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n', 'ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96'], 'total': 998000, 'fees': 2000, 'size': 116, 'vsize': 116, 'preference': 'medium', 'relayed_by': '2409:40c4:2024:fd65:5d75:19be:c178:e4cd', 'received': '2024-08-14T07:15:31.933724924Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c1b684d4975625ed16eb66ace32435f68cc4308f1b5689151173f1196bb5e97a', 'output_index': 0, 'output_value': 1000000, 'sequence': 4294967295, 'addresses': ['ltc1q4zrw4yf369t3tv2uqdypp65w2x9gvxz38npw96'], 'script_type': 'pay-to-witness-pubkey-hash', 'age': 2737893}], 'outputs': [{'value': 998000, 'script': '00148cef6940c2d37e964856c390acd7db5d93ee8218', 'addresses': ['ltc1q3nhkjsxz6dlfvjzkcwg2e47mtkf7aqscm5su4n'], 'script_type': 'pay-to-witness-pubkey-hash'}]}, 'tosign': ['0d47ffcacb04cc061171b70685158ec8108ab0dbffc2b6c5f116cb5ca7002e22']}
Signed signatures: ['3045022100fe093a487021012e066866a74c074c2d961b2dbd7ec1dc9e3029c2ed206e884602204f002aece0c2aa3e9ef7e43c30f248fb9240d5efa2083d0e6d108297411d779101']
